### PR TITLE
[14.0] [MIG] account_move_line_report_xls

### PR DESCRIPTION
**Pull request by PieterPaulussen**

### CODE REVIEW

**Review by rconjour — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
See upstream PR for my review.

**Comment by StefanRijnhart** [comment]
Looks like you need to rebase and install pre-commit in your local branch

**Comment by StefanRijnhart** [comment]
This PR shows two commits that are already in the target branch. Can you try to rebase the branch to solve this?

**Comment by PieterPaulussen** [comment]
@StefanRijnhart dragged along some commits from the upstream. Rebased 14.0-nova and this branch.
Now I still need to solve that shitty error In the CI that has been haunting me at night.

**Comment by StefanRijnhart** [comment]
Ah the bitbucket PR links to here as the OCA PR so that's why I noticed the commits.

**Review by rconjour — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
